name       : opam
version    : 2.1.4
release    : 7
source     :
    - https://github.com/ocaml/opam/releases/download/2.1.4/opam-full-2.1.4.tar.gz : 1643609f4eea758eb899dc8df57b88438e525d91592056f135e6e045d0d916cb
homepage   : https://opam.ocaml.org/
license    : LGPL-2.1-only WITH OCaml-LGPL-linking-exception
component  : programming.tools
summary    : Source-based package manager for OCaml
description: |
    opam is a source-based package manager for OCaml. It supports multiple simultaneous compiler installations, flexible package constraints, and a Git-friendly development workflow.
builddeps  :
    - ocaml
rundeps    :
    - bubblewrap
    - ocaml
setup      : |
    %configure
build      : |
    %make lib-ext -j1 OCAMLC="ocamlc -unsafe-string" OCAMLOPT="ocamlopt -unsafe-string"
    %make -j1 OCAMLC="ocamlc -unsafe-string" OCAMLOPT="ocamlopt -unsafe-string"
install    : |
    %make_install
